const STYLES = {
    container: {
        width: '100%',
        height: '100%',
        backgroundColor: '#050505',
        color: '#ffffff',
        fontFamily: '"Outfit", "Inter", sans-serif',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
    },
    header: {
        padding: '15px 25px',
        borderBottom: '1px solid #2d2d2d',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        background: '#0a0a0a',
    },
    title: {
        fontSize: '20px',
        fontWeight: '700',
        background: 'linear-gradient(135deg, #a78bfa, #f472b6)',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
    },
    content: {
        flex: 1,
        display: 'flex',
        padding: '20px',
        gap: '20px',
        minHeight: 0,
    },
    previewArea: {
        flex: 2,
        display: 'flex',
        flexDirection: 'column',
        gap: '15px',
        minWidth: 0,
    },
    controlsArea: {
        flex: 1,
        background: '#111',
        borderRadius: '16px',
        border: '1px solid #2d2d2d',
        padding: '20px',
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
        minWidth: '300px',
        maxWidth: '400px',
    },
    canvasContainer: {
        flex: 1,
        background: '#0a0a0a',
        backgroundImage: `
      linear-gradient(45deg, #151515 25%, transparent 25%),
      linear-gradient(-45deg, #151515 25%, transparent 25%),
      linear-gradient(45deg, transparent 75%, #151515 75%),
      linear-gradient(-45deg, transparent 75%, #151515 75%)
    `,
        backgroundSize: '20px 20px',
        backgroundPosition: '0 0, 0 10px, 10px -10px, -10px 0px',
        borderRadius: '16px',
        border: '1px solid #333',
        position: 'relative',
        overflow: 'hidden',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        boxShadow: '0 10px 30px rgba(0,0,0,0.5)',
    },
    button: {
        padding: '12px 20px',
        borderRadius: '8px',
        border: 'none',
        background: '#8b5cf6',
        color: 'white',
        fontWeight: '600',
        cursor: 'pointer',
        transition: 'all 0.2s',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
    },
    inputGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    label: {
        fontSize: '12px',
        color: '#999',
        textTransform: 'uppercase',
        letterSpacing: '1px',
        fontWeight: '700',
    },
    range: {
        width: '100%',
        accentColor: '#8b5cf6',
    }
};

return { STYLES };
