const STYLES = {
  fullTabWrapper: {
    position: "relative",
    height: "100%",
    width: "100%",
    padding: "20px",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    backgroundColor: "var(--background-secondary)",
    border: "1px solid var(--background-modifier-border)",
    borderRadius: "8px",
    color: "var(--text-normal)",
  },
  iconContainer: {
    position: "absolute",
    top: "15px",
    right: "20px",
    fontFamily: "monospace",
    fontSize: "14px",
    color: "var(--text-faint)",
    userSelect: "none",
    cursor: "pointer",
    zIndex: 10,
  },
  tooltip: {
    visibility: "hidden",
    opacity: 0,
    backgroundColor: "var(--background-secondary-alt)",
    color: "var(--text-normal)",
    textAlign: "center",
    borderRadius: "4px",
    padding: "5px 10px",
    position: "absolute",
    zIndex: 1,
    top: "50%",
    right: "120%",
    transform: "translateY(-50%)",
    fontSize: "12px",
    whiteSpace: "nowrap",
    pointerEvents: "none",
    border: "1px solid var(--background-modifier-border)",
  },
  reloadButton: {
    position: "absolute",
    top: "12px",
    right: "50px",
    zIndex: 10,
    width: "30px",
    height: "30px",
    borderRadius: "50%",
    border: "none",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    color: "var(--text-faint)",
    outline: "none",
    padding: 0,
    backgroundColor: "transparent",
  },
  title: { 
    fontSize: "2em", 
    fontWeight: "600", 
    color: "var(--text-normal)" 
  },
  subtitle: {
    fontSize: "1em",
    color: "var(--text-muted)",
    maxWidth: "400px",
    textAlign: "center",
    fontFamily: "monospace",
  },
  compactWrapper: {
    padding: "16px",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "12px",
    border: "1px dashed var(--background-modifier-border)",
    borderRadius: "8px",
    backgroundColor: "var(--background-primary-alt)",
  },
  compactText: { 
    margin: 0, 
    color: "var(--text-muted)", 
    fontSize: "14px" 
  },
  buttonGroup: { 
    display: "flex", 
    gap: "10px" 
  },
  button: {
    padding: "8px 16px",
    fontSize: "12px",
    fontWeight: "500",
    color: "var(--text-on-accent)",
    backgroundColor: "var(--interactive-accent)",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
  },
  secondaryButton: {
    backgroundColor: "var(--background-modifier-hover)",
    color: "var(--text-muted)",
  },
};

return { STYLES };